import { getStatic, listStatic, searchStatic, type PortalCard, type PortalType } from "./lib/staticPortal";

const app = document.querySelector<HTMLDivElement>("#app")!;
const base = import.meta.env.BASE_URL;
const href = (route: string) => `${base}#${route}`;
const domains = listStatic("domain", 20);
const nav = [
  ["/", "Beranda"], ["/start-here", "Mulai dari sini"], ["/search", "Cari materi"],
  ["/glossary", "Glosarium"], ["/faq", "FAQ"], ["/documents", "Sumber dokumen"]
] as const;
const esc = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char] ?? char));
const text = (value: unknown): string => Array.isArray(value) ? value.map(text).join(" ") : typeof value === "object" && value ? Object.values(value as Record<string, unknown>).map(text).join(" ") : String(value ?? "");
const statusLabel = (status: string) => ({SOURCE_SUPPORTED:"Didukung sumber",PARTIAL_EVIDENCE:"Bukti sebagian",CONFLICTING:"Konflik",REQUIRES_HUMAN_REVIEW:"Perlu tinjauan manusia"}[status] ?? status.replaceAll("_", " "));
const domainCopy: Record<string, string> = { D01:"Pahami bagaimana komitmen lingkungan diterjemahkan menjadi pelaksanaan, pemantauan, dan pelaporan.", D02:"Kenali hubungan antara peraturan, izin, persetujuan, dan bukti pelaksanaan.", D03:"Pelajari alur pemantauan dari perencanaan titik sampling sampai validasi hasil.", D04:"Pahami materi pemantauan kualitas air, air limbah, parameter, dan pelaporannya.", D05:"Pelajari pemantauan emisi dan udara ambien berdasarkan sumber yang tersedia.", D06:"Kenali jenis limbah, bukti pengelolaan, serta hal yang masih membutuhkan verifikasi.", D07:"Pelajari kegiatan laut, dumping, pengerukan, sampling, dan keterbatasan bukti.", D08:"Kenali materi keanekaragaman hayati, survei sosial, mangrove, dan revegetasi.", D09:"Pahami hubungan data energi, emisi, KPI, validasi, pelaporan, dan pengarsipan.", D10:"Pelajari materi pelaporan lingkungan, PROPER, LCA, GHG, dan perbaikan berkelanjutan.", D11:"Pahami peran, koordinasi, pelatihan, penutupan kontrak, dan sistem manajemen lingkungan." };
const domainConcepts: Record<string, string> = { D01:"AMDAL/RKL-RPL, pelaporan pelaksanaan, survei lokasi, dan pelaporan", D02:"Peraturan, izin, persetujuan, dan kepatuhan", D03:"Pemantauan, titik sampling, laboratorium, validasi, dan pelaporan", D04:"Kualitas air, air limbah, parameter, izin, dan data", D05:"Sumber emisi, udara ambien, flaring, dan pelaporan", D06:"Limbah umum, B3/LB3, lumpur pemboran, penyimpanan, dan pengangkutan", D07:"Lingkungan laut, dumping, pengerukan, dan material pemboran", D08:"Keanekaragaman hayati, survei sosial, mangrove, dan revegetasi", D09:"Energi, emisi, KPI, validasi, pelaporan, dan pengarsipan", D10:"Manajemen lingkungan, PROPER, LCA, GHG, dan perbaikan", D11:"Peran, koordinasi, pelatihan, penutupan kontrak, dan sistem manajemen" };
const gapCopy = ["Metadata revisi, status persetujuan, dan tanggal berlaku belum lengkap pada sebagian dokumen.", "Nilai ambang atau baku mutu berbeda antar dokumen dan belum tersusun dalam satu tabel penerapan.", "Kriteria keputusan serta penanggung jawab untuk beberapa alur belum dijelaskan secara rinci dalam sumber."];
const titleFor = (type: PortalType, item: PortalCard) => type === "domain" ? ({D01:"AMDAL dan RKL-RPL",D02:"Perizinan dan kepatuhan hukum",D03:"Pemantauan, sampling, dan laboratorium",D04:"Air dan air limbah",D05:"Emisi udara dan udara ambien",D06:"Limbah, B3/LB3, dan material pemboran",D07:"Lingkungan laut, dumping, dan pengerukan",D08:"Keanekaragaman hayati dan sosial",D09:"Gas rumah kaca dan energi",D10:"Data lingkungan dan pelaporan",D11:"Sistem manajemen lingkungan"}[item.id] ?? item.title) : item.title;
const card = (item: PortalCard, route: string, index?: number) => `<a class="card" href="${href(route)}"><div style="display:flex;justify-content:space-between;gap:10px"><span class="number">${index !== undefined ? String(index + 1).padStart(2,"0") : esc(item.type.toUpperCase())}</span><span class="status">${esc(statusLabel(item.status))}</span></div><h3>${esc(titleFor(item.type, item))}</h3><p>${esc(summary(item))}</p></a>`;
function summary(item: PortalCard) { if (item.type === "domain" && domainCopy[item.id]) return domainCopy[item.id]; const data = item.data; return text(data.summary ?? data.description ?? data.purpose ?? data.intro ?? "Catatan teraudit dari kumpulan sumber lingkungan.").slice(0, 220); }
function shell(content: string, active = "/") { app.innerHTML = `<div class="shell"><header class="topbar"><a class="brand" href="${href("/")}"><span class="brand-mark">E</span><span><strong>Environment</strong><small>Basis Pengetahuan</small></span></a><div class="toplinks"><span>Portal baca-saja</span><a href="${href("/search")}">Cari materi</a></div></header><div class="layout"><aside class="sidebar"><h2>Menu belajar</h2><nav class="nav">${nav.map(([route,label]) => `<a class="${active === route ? "active" : ""}" href="${href(route)}">${label}</a>`).join("")}</nav></aside><main class="main">${content}<footer class="footer">Materi ditampilkan untuk pembelajaran berdasarkan sumber teraudit. Status bukti dan keterbatasan tetap dipertahankan.</footer></main></div></div>`; }
function home() { shell(`<section class="hero"><p class="eyebrow">Portal belajar lingkungan</p><h1>Pilih aspek yang ingin Anda pelajari.</h1><p>Mulai dari aspek yang paling dekat dengan kebutuhan Anda. Materi, konsep inti, tugas terkait, dan sumber ditampilkan langsung di halaman ini.</p><div class="actions"><a class="button" href="${href("/start-here")}">Lihat cara mulai →</a><a class="button secondary" href="${href("/search")}">Cari materi</a></div></section><div class="section-head"><div><p class="eyebrow" style="color:#277345">Peta belajar</p><h2>11 aspek lingkungan</h2><p class="muted">Pilih satu kartu untuk membaca materi pengantar. Anda tidak perlu membuka file ZIP.</p></div></div><div class="grid">${domains.map((item,index) => card(item, `/learn/${item.id}`, index)).join("")}</div>`, "/"); }
function startHere() { shell(`<div class="content"><a class="back" href="${href("/")}">← Kembali ke Beranda</a><p class="eyebrow">Mulai di sini</p><h1>Alur belajar sederhana</h1><div class="panel"><h2>1. Pilih aspek</h2><p>Mulai dari salah satu dari 11 aspek lingkungan. Baca ringkasan, konsep, keterbatasan, dan sumbernya.</p></div><div class="panel"><h2>2. Baca status bukti</h2><p>Perhatikan label <strong>Bukti sebagian</strong>, konflik, dan catatan yang membutuhkan verifikasi manusia. Portal ini tidak mengubah isi sumber menjadi kepastian baru.</p></div><div class="panel"><h2>3. Telusuri sumber</h2><p>Gunakan pencarian lokal, glosarium, dan panel sitasi untuk menemukan dokumen yang mendasari setiap catatan.</p></div><div class="actions"><a class="button" href="${href("/learn/D01")}">Mulai dari AMDAL →</a><a class="button secondary" href="${href("/search")}">Cari istilah</a></div></div>`, "/start-here"); }
function learning(id: string) { const item = getStatic("domain", id); if (!item) { shell(`<div class="empty"><h2>Materi tidak ditemukan</h2><p>Aspek ini belum cocok dengan ID sumber. Kembali ke daftar aspek.</p><a class="button" href="${href("/")}">Kembali ke Beranda</a></div>`); return; } const data = item.data; const terms = listStatic("glossary", 12); const gaps = listStatic("gap", 8); shell(`<div class="content"><a class="back" href="${href("/")}">← Kembali memilih aspek</a><p class="eyebrow">Materi aspek</p><h1>${esc(titleFor("domain", item))}</h1><p class="muted">${esc(summary(item))}</p><span class="status">${esc(statusLabel(item.status))}</span><div class="panel"><h2>Ringkasan yang perlu dipahami</h2><p>${esc(summary(item))}</p></div><div class="panel"><h2>Konsep inti</h2><div class="chips">${(domainConcepts[item.id] ?? text(data.core_concepts ?? data.key_concepts ?? data.concepts ?? "Istilah inti tercatat dalam sumber terkait.")).split(/[,;|]/).filter(Boolean).slice(0,10).map((term: string) => `<span class="chip">${esc(term.trim())}</span>`).join("")}</div></div><div class="panel"><h2>Apa yang perlu diperhatikan</h2><p class="muted">Keterbatasan berikut ditampilkan agar pembaca tidak menganggap catatan sebagai kepastian operasional.</p><ul>${gapCopy.map(gap => `<li>${esc(gap)}</li>`).join("")}</ul></div><div class="panel"><h2>Istilah yang berkaitan</h2><div class="chips">${terms.slice(0,8).map(term => `<a class="chip" href="${href(`/glossary?id=${encodeURIComponent(term.id)}`)}">${esc(term.title)}</a>`).join("")}</div></div><div class="panel sources"><h2>Bukti & sumber</h2>${item.refs.length ? item.refs.map(ref => `<div class="source">${esc(ref)}</div>`).join("") : `<p>Referensi sumber belum tercatat.</p>`}</div></div>`, "/"); }
function searchPage() { const query = new URLSearchParams(location.hash.split("?")[1] ?? "").get("query") ?? ""; const results = query ? searchStatic(query, undefined, undefined, 40) : []; shell(`<div class="content"><p class="eyebrow">Pencarian lokal</p><h1>Cari materi</h1><p class="muted">Pencarian berjalan di browser menggunakan katalog materi yang dibundel. Tidak ada API atau login.</p><form class="searchbar" id="search-form"><input id="query" value="${esc(query)}" placeholder="Contoh: sampling air, AMDAL, limbah" aria-label="Cari materi"/><button class="button" type="submit">Cari</button></form>${query ? `<p class="muted">${results.length} hasil untuk “${esc(query)}”</p><div class="grid">${results.map(item => card(item, item.type === "domain" ? `/learn/${item.id}` : `/search?query=${encodeURIComponent(item.title)}`)).join("") || `<div class="empty">Tidak ada hasil. Coba istilah lain.</div>`}</div>` : `<div class="panel"><h2>Coba pencarian pertama</h2><p>Gunakan istilah seperti <strong>sampling</strong>, <strong>AMDAL</strong>, <strong>air limbah</strong>, atau <strong>limbah B3</strong>.</p></div>`}</div>`, "/search"); document.querySelector<HTMLFormElement>("#search-form")?.addEventListener("submit", event => { event.preventDefault(); const value = (document.querySelector<HTMLInputElement>("#query")?.value ?? "").trim(); location.hash = `/search?query=${encodeURIComponent(value)}`; }); }
function glossary() { const items = listStatic("glossary", 120); shell(`<div class="content"><p class="eyebrow">Istilah sumber</p><h1>Glosarium</h1><p class="muted">Istilah berikut dipertahankan dari kumpulan sumber dan tidak otomatis berlaku untuk semua kegiatan.</p><div class="grid">${items.map(item => `<article class="card"><h3>${esc(item.title)}</h3><p>${esc(text(item.data.definition ?? item.data.description ?? item.data.meaning ?? "Informasi definisi tidak ditemukan dalam sumber saat ini."))}</p><div class="source">${esc(item.refs[0] ?? "Referensi belum tercatat")}</div></article>`).join("")}</div></div>`, "/glossary"); }
function faq() { shell(`<div class="content"><p class="eyebrow">Bantuan membaca portal</p><h1>FAQ</h1>${[["Apakah portal ini menggantikan dokumen asli?","Tidak. Portal ini membantu menemukan dan memahami materi. Selalu buka sumber dan periksa status buktinya sebelum mengambil keputusan."],["Mengapa ada label Bukti sebagian?","Karena materi sumber tidak selalu memuat metadata, prosedur, tanggal berlaku, atau detail lengkap. Kekosongan tidak diisi dengan asumsi."],["Bagaimana menemukan materi tertentu?","Gunakan Pencarian pada menu. Masukkan istilah sederhana seperti sampling, AMDAL, atau air limbah."],["Apakah saya harus login?","Tidak. Portal ini sengaja dibuat baca-saja tanpa login, AI, serah terima, atau pengiriman data."]].map(([q,a]) => `<details class="panel"><summary><strong>${q}</strong></summary><p>${a}</p></details>`).join("")}</div>`, "/faq"); }
function documents() { const items = listStatic("document", 80); shell(`<div class="content"><p class="eyebrow">Jejak sumber</p><h1>Sumber dokumen</h1><p class="muted">Daftar dokumen yang membentuk katalog materi. Nama dan status ditampilkan apa adanya dari metadata sumber.</p><div class="grid">${items.map(item => `<article class="card"><span class="status">${esc(statusLabel(item.status))}</span><h3>${esc(item.title)}</h3><p>${esc(text(item.data.relative_path ?? item.data.path ?? item.data.filename ?? "Lokasi sumber tidak tercatat."))}</p><div class="source">${esc(item.id)}</div></article>`).join("")}</div></div>`, "/documents"); }
function render() { const raw = location.hash.replace(/^#/, "") || "/"; const [path] = raw.split("?"); if (path.startsWith("/learn/")) return learning(path.split("/")[2] ?? ""); if (path === "/start-here") return startHere(); if (path === "/search") return searchPage(); if (path === "/glossary") return glossary(); if (path === "/faq") return faq(); if (path === "/documents") return documents(); return home(); }
window.addEventListener("hashchange", render); render();
